<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="FB_Conveyor" Id="{cd65f802-7882-40c4-9d72-4194747e95ad}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Conveyor

VAR_INPUT
    bStart          : BOOL;
    bStop           : BOOL;
    bReset          : BOOL;
    bEmergencyStop  : BOOL;
END_VAR

VAR_OUTPUT
    stStatus        : ST_ConveyorStatus;
END_VAR

VAR
    bStartMemory    : BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>